### ISSUE TITLE
deleting nupic.cerebro

### ISSUE THREAD

**Issue by breznak** [numenta/nupic.cerebro#8]
in favor of nupic.cerebro2 ? @chetan51 @rhyolight

**Comment by rhyolight** [comment]
:+1: I don't think anyone has used it in over a year. @yakticus didn't you attempt to use it last year?

**Comment by rhyolight** [comment]
Although I'm not in favor of complete deletion. I'd rather mark as deprecated so the source is still around for future reference.

**Comment by chetan51** [comment]
I'm in favor of deprecation.

**Comment by jefffohl** [comment]
Yes - I also favor deprecation over deletion.
